first commit
vladimirmuratov/react-burger pull request #5
Opened 2021-08-29 10:54 UTC by vladimirmuratov

2021-08-29 18:11 UTC, vladimirmuratov commented
Прошу смотреть second commit

2021-08-30 11:23 UTC, SmilingJey requested changes
Здравствуйте!

В целом хорошая работа, сверстаны необходимые страницы, настроен роутинг и большая часть функционала работает верно. Но есть несколько замечаний:

**Основные замечания которые необходимо исправить:**

- при прямом переходе на страницу ингредиента не отображается страница ингредиента, как по заданию, а попадаем на главную

- по заданию  в случае успешной отправки запроса восстановления пароля пользователь направляется на маршрут /reset-password

- после успешной авторизации должен происходить редирект на тот маршрут, к которому пользователь не получил доступ ранее

- не нужна отдельная страница для выхода

- после выхода должен быть переход на /login

- если запрос до сервера не дошел или сервер вообще не ответил то продолжает отображаться прелоадер

- проверка ошибки истечения времени жизни токена и его перезапрос нужны во всех запросах, которых требуют авторизации

**Более подробно эти и более мелкие мелкие замечания, а так же места в которых можно улучшить проект, отмечены в коде:**

2021-08-30 11:23 UTC, SmilingJey commented on src/services/user/actions.js
> +        console.log('Что-то пошло не так...', e)
**Надо исправить** 

здесь и для все остальных запросов, если запрос до сервера не дошел или сервер вообще не ответил, то мы попадем в этот catch , т.к. fetch выбросит ошибку , а здесь мы никак не обрабатываем ошибка кроме вывода в консоль. Получается прелоадер продолжает вечно отображаться, если сервер не ответил на запрос (нет интернета или упал сам сервер)

![2021-08-30_13-53-31](https://user-images.githubusercontent.com/9317133/131329205-584f2a25-8a9d-4fcd-bb2e-4dd631b44a0b.png)

Нужно добавить сюда тоже обработку ошибки с советующим диспатчем

А лучше добавить проверку в самих функциях Api 

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

export const loginUserRequest = (data) => {
    return fetch(URL_LOGIN_USER, {
        method: 'POST',
        body: JSON.stringify(data),
        headers: {
            'Content-Type': 'application/json'
        }
    })
        .then(checkReponse )
}

```

Тогда выполнение запроса будет выглядеть так

```
export const postLoginData = (data) => async dispatch => {

    dispatch({
        type: LOGIN_START
    })

    try {
        const res = await loginUserRequest(data)
                    dispatch({
                        type: LOGIN_SUCCESS,
                        payload: res
                   })
    } catch (e) {
                    dispatch({
                        type: LOGIN_FAILED,
                        payload: res.message
                    })
    }
}
```

и не смешивайте await и then , это плохой тон , выглядит как будто Вы хотите использовать await , но не до конца разобрались как он работает

2021-08-30 11:23 UTC, SmilingJey commented on src/services/user/actions.js
> +            })
**Надо исправить**

проверка ошибки истечения времени жизни токена и его перезапрос нужны во всех запросах, которых требуют авторизации, а не только в получение данных пользователя

Нужно добавить и в updateProfileData и logout

2021-08-30 11:23 UTC, SmilingJey commented on src/pages/login/login.jsx
> +            history.replace({pathname: '/'})
**Надо исправить**

После успешной авторизации должен происходить редирект на тот маршрут, к которому пользователь не получил доступ ранее. 

Например, пользователь попытался перейти напрямую на страницу профиля, его перенаправило на вход и после успешного логина пользователь должен попапасть сразу на страницу профиля, а не на главную

2021-08-30 11:23 UTC, SmilingJey commented on src/pages/logout/logout.jsx
> +                history.replace({pathname: '/'})
**Надо исправить**

после выхода по заданию должен быть переход на /login

2021-08-30 11:23 UTC, SmilingJey commented on src/components/switch-modal/switch-modal.jsx
> +    let background = location.state && location.state.background
**Надо исправить**

 при прямом переходе не отображается страница ингредиента, как по заданию, а попадаем на главную

![2021-08-30_14-16-52](https://user-images.githubusercontent.com/9317133/131331628-f68ad6a6-030c-40fb-9ddb-ce85f03c2563.png)

2021-08-31 17:30 UTC, vladimirmuratov commented
По поводу вашего замечания: при прямом переходе не отображается страница ингредиента, как по заданию, а попадаем на главную.
Наставник нам объяснил задачу так: при клике по ингредиенту появляется попап и в url добавляется '/ingredients/:id'. Копируем этот url и отправляем другу по email. Человек кликает по этой ссылке и попадает на страницу с описанием этого ингредиента. Этот функционал я и реализовал, это работает. Все остальные замечания, обязательные к устранению, я исправил

2021-08-31 17:35 UTC, SmilingJey commented
В задании прямо сказано, что даже при обновлении страницы пользователь должен попасть на страницу ингредиента

![2021-08-31_20-33-06](https://user-images.githubusercontent.com/9317133/131549479-f87b10fb-bbb7-47c9-b6ec-b8b5c3c23d2f.png)

реализация когда адрес ингредиента, но при этом отображается главная страница, некорректна, возможно вы неправильно поняли наставника

2021-09-01 07:54 UTC, SmilingJey requested changes
Часть замечаний исправлено, но несколько проблем осталось:

- при обновлении страницы после открытия попапа ингредиента пользователь должен попасть на страницу ингредиента, это требование есть в задании. Сейчас он остается на главной, хотя в адресной строке адрес ингредиента

- при ошибке входе и регистрации страница падает с ошибкой, сообщение об ошибке нужно брать не из res, а из ошибки

- если неавторизированный пользователь переходит по прямой ссылке на /profile, то записываются undefined в refreshTocken
![2021-09-01_10-48-31](https://user-images.githubusercontent.com/9317133/131633705-9dc68123-e296-4d5f-ab17-fa7b4c97a51e.png)
и начинается непрерывная циклическая отправка запросов
![2021-09-01_10-48-46](https://user-images.githubusercontent.com/9317133/131633959-04e909ca-da31-4a1c-a9d9-61116a089907.png)

2021-09-01 07:54 UTC, SmilingJey commented on src/services/user/actions.js
> +            payload: res.message
**Надо исправить**

**здесь и в аналогичных местах** нужно использовать ошибку "e", а не res, сейчас при ошибке входа страница падает т.к. res при ошибке пуст

![2021-09-01_10-29-38](https://user-images.githubusercontent.com/9317133/131632789-ea98d269-cde8-4a3a-943d-b6e4e6b562ea.png)

2021-09-01 13:43 UTC, vladimirmuratov commented
Добрый день!
По поводу вашего замечания: при обновлении страницы после открытия попапа ингредиента пользователь должен попасть на страницу ингредиента, это требование есть в задании. Сейчас он остается на главной, хотя в адресной строке адрес ингредиента
Обсудил этот момент с наставником. Он мне сказал добавить в функцию закрытия попап history.goBack(), что я и сделал. Остальные замечания тоже устранил.
P.S. Спасибо за ваше терпение...)))

2021-09-01 15:35 UTC, SmilingJey requested changes
Одно замечание исправлено, но два осталось:

- показал как сделать, что бы при обновлении страницы был переход на страницу ингредиента как по заданию (нужна проверка history.action)

- все ещё есть циклическая отправка запроса рефреша токена, добавьте во все запросы проверку checkResponse

2021-09-01 15:35 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.jsx
> +
history.goBack() вообще ничего не дает, т.к. при рефреше страницы не происходит вызов закрытия окна, нужно добавить проверку какое дествие было произведено при переходе на страницу history.action

```
    const action = history.action ==='PUSH' || history.action ==='REPLACE';
    let background = action && location.state && location.state.background
```

2021-09-01 15:35 UTC, SmilingJey commented on src/api/api.js
> +        .then(res => res.json())
нет проверки checkResponse , поэтому при переходе на /profile неавторизированным пользователем начинается циклическая проверка токена

![2021-09-01_18-30-29](https://user-images.githubusercontent.com/9317133/131700036-dbc9bc87-750e-4c60-81ac-6c29567b8833.png)

Сервер при проверке возвращает ошибку, несмотря на ошибку мы попадаем в then, т.к. нет проверки успешности запроса. 
Вызывается код
```
            localStorage.setItem('refreshToken', res.refreshToken)
            setCookie('accessToken', res.accessToken)
            dispatch(afterRefresh)
```

который записывает undefined в стор и cookies, потом диспатчится экшен переданный в afterRefresh, запрос которого опять падает с ошибкой и снова вызывается refreshToken и так по кругу

Добавьте checkResponse  во все запросы

2021-09-01 15:38 UTC, SmilingJey commented on src/components/switch-modal/switch-modal.jsx
> +    let background = (history.action === 'PUSH' || history.action === 'REPLACE') && location.state && location.state.background
history.goBack() не решит проблему, т.к. при рефреше страницы не происходит вызов закрытия окна, нужно добавить проверку какое действие было произведено при переходе на страницу (history.action)

```
    const action = history.action ==='PUSH' || history.action ==='REPLACE';
    let background = action && location.state && location.state.background
```

2021-09-01 15:38 UTC, vladimirmuratov commented
Только что получил уточнение от наставника. Прошу смотреть fifth commit. Теперь правильно

2021-09-01 15:38 UTC, SmilingJey commented
поправьте это замечание ещё https://github.com/vladimirmuratov/react-burger/pull/5#discussion_r700330335

2021-09-01 16:47 UTC, vladimirmuratov commented
Исправил. Надеюсь уложился в отведенное количество попыток )))

2021-09-02 07:52 UTC, SmilingJey commented
Отлично, замечания исправлены

Успехов в дальнейшем обучении!

2021-09-02 12:01 UTC, merged